# Generated by Django 4.2.5 on 2023-09-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='../static/assets/img/default_avatar.png', null=True, upload_to='midia/users/%Y/%m/%d/', verbose_name='Avatar'),
        ),
    ]
