# Generated by Django 4.2.5 on 2023-12-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='users',
            new_name='user',
        ),
    ]
