# Generated by Django 5.0 on 2024-01-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonus_points',
            field=models.FloatField(default=0, verbose_name='Бонусные баллы'),
        ),
    ]
