# Generated by Django 5.0 on 2024-01-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuswallet',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Balance'),
        ),
    ]
