# Generated by Django 5.0 on 2024-01-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_bonuswallet_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='seil',
            new_name='sale',
        ),
    ]
