# Generated by Django 4.2.5 on 2023-09-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, unique='items/%Y/%m/%d/', upload_to='')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('discount_price', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
