# Generated by Django 4.2.5 on 2023-09-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='item',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='items/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='item',
            name='compound',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='delivery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
