# Generated by Django 4.2.5 on 2023-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_category_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ManyToManyField(blank=True, null=True, related_name='cert_image', to='items.certificateimages', verbose_name='Сертификаты'),
        ),
    ]
