# Generated by Django 4.2.5 on 2023-09-07 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_photo_certificateimages_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateimages',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.category', verbose_name='Категория'),
        ),
    ]
