# Generated by Django 4.2.5 on 2023-09-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_certificateimages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
    ]
