# Generated by Django 4.2.5 on 2023-09-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/images/%Y/%m/%d/'),
        ),
    ]
