# Generated by Django 4.2.5 on 2023-09-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='brends/images/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
