# Generated by Django 4.2.5 on 2023-09-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_brend_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brend',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.brend', verbose_name='Бренд'),
        ),
    ]
