# Generated by Django 4.2.5 on 2023-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_remove_brend_item_item_brend'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seil_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
