# Generated by Django 4.2.5 on 2023-10-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/%Y/%m/%d/', verbose_name='Изображение товара'),
        ),
    ]
