# Generated by Django 4.2.5 on 2023-10-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_cart_items_alter_cartitem_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promocode',
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='items.cartitem', verbose_name='Товары в корзине'),
        ),
    ]
