# Generated by Django 4.2.5 on 2023-11-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_cart_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Процент бонусных баллов'),
        ),
    ]
