# Generated by Django 4.2.5 on 2023-11-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_item_bonus_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bonus_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=15, max_digits=5, null=True, verbose_name='Процент бонусных баллов'),
        ),
    ]
