# Generated by Django 4.2.5 on 2023-11-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_remove_cart_items_cart_cart_items_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='items.CartItem', to='items.item', verbose_name='Товары в корзине'),
        ),
    ]
