# Generated by Django 4.2.5 on 2023-11-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_remove_cart_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Товар выбран для заказа в корзине'),
        ),
    ]
