# Generated by Django 4.2.5 on 2023-11-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_cartitem_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
