# Generated by Django 4.2.5 on 2023-11-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_alter_cartitem_unique_together_remove_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session',
        ),
    ]
