# Generated by Django 4.2.5 on 2023-12-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0034_alter_favoriteitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
