# Generated by Django 5.0 on 2024-01-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0036_alter_item_bonus_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bonus_percentage',
            field=models.FloatField(default=15, verbose_name='Процент бонусных баллов'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка %'),
        ),
    ]
