# Generated by Django 5.0 on 2024-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0037_alter_item_options_itemviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
