# Generated by Django 5.0 on 2024-01-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_remove_promocode_sale_promocode_discount'),
        ('items', '0037_alter_item_bonus_percentage_alter_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balance.promocode', verbose_name='Промокод'),
        ),
    ]
