# Generated by Django 5.0 on 2024-01-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0038_cartitem_promocode'),
        ('items', '0038_item_views_count'),
    ]

    operations = [
    ]
