# Generated by Django 5.0 on 2024-01-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0039_merge_0038_cartitem_promocode_0038_item_views_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.DeleteModel(
            name='ItemViews',
        ),
    ]
