# Generated by Django 5.0 on 2024-01-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0041_alter_item_image_itemimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimages',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AddField(
            model_name='certificateimages',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/'),
        ),
    ]
