# Generated by Django 5.0 on 2024-01-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0042_alter_itemimages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateimages',
            name='photo',
        ),
        migrations.AlterField(
            model_name='certificateimages',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/', verbose_name='PDF Сертификат (не изображение!)'),
        ),
    ]
