# Generated by Django 5.0 on 2024-01-29 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0043_remove_certificateimages_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Активное вещество')),
            ],
            options={
                'verbose_name': 'Активное вещество',
                'verbose_name_plural': 'Активные вещества',
            },
        ),
        migrations.AlterModelOptions(
            name='certificateimages',
            options={'verbose_name': 'PDF Сертификат', 'verbose_name_plural': 'PDF Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='itemimages',
            options={'verbose_name': 'PNG Фото товара', 'verbose_name_plural': 'PNG Фото товаров'},
        ),
        migrations.AlterField(
            model_name='itemimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Только PNG фото!'),
        ),
        migrations.AddField(
            model_name='item',
            name='active_bad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.bads', verbose_name='Активное вещество'),
        ),
    ]
