# Generated by Django 5.0 on 2024-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0047_alter_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул'),
        ),
    ]
