# Generated by Django 5.0 on 2024-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0051_item_users_waiting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='active_bad',
        ),
        migrations.AddField(
            model_name='item',
            name='active_bads',
            field=models.ManyToManyField(blank=True, to='items.bads', verbose_name='Активное вещество'),
        ),
    ]
