# Generated by Django 5.0 on 2024-02-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0053_delete_bads_alter_activebad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка %'),
        ),
    ]
