# Generated by Django 5.0 on 2024-02-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0054_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
