# Generated by Django 5.0 on 2024-02-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0055_rename_title_category_name'),
        ('items', '0056_review_user_alter_review_item'),
    ]

    operations = [
    ]
