# Generated by Django 5.0 on 2024-02-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0058_alter_item_discount_alter_review_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка %'),
        ),
    ]
