# Generated by Django 5.0 on 2024-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0061_remove_item_category_item_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрыть товар'),
        ),
    ]
