# Generated by Django 4.2.5 on 2023-09-11 10:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Краткий заголовок акции')),
                ('text', models.CharField(max_length=255, verbose_name='Краткое описание акции')),
                ('image', models.ImageField(upload_to='sales/images/%Y/%m/%d/', verbose_name='Картинка акции')),
                ('context', ckeditor.fields.RichTextField(verbose_name='Контент страницы')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='SliderTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='baners/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Верхний слайдер',
                'verbose_name_plural': 'Верхние слайдеры',
            },
        ),
        migrations.CreateModel(
            name='SliderTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='baners/%Y/%m/%d/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Нижний слайдер',
                'verbose_name_plural': 'Нижние слайдеры',
            },
        ),
    ]
