# Generated by Django 4.2.5 on 2023-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidertop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slidertwo',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
