# Generated by Django 4.2.5 on 2023-09-12 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_slidertop_slug_alter_slidertwo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
