# Generated by Django 4.2.5 on 2023-09-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_sale_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='partners/images/%Y/%m/%d/')),
                ('site', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Партнеры',
            },
        ),
    ]
