# Generated by Django 4.2.5 on 2023-10-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidertop',
            name='image',
            field=models.ImageField(upload_to='sliders/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='slidertwo',
            name='image',
            field=models.ImageField(upload_to='sliders/%Y/%m/%d/'),
        ),
    ]
