# Generated by Django 4.2.5 on 2023-10-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedpromocode',
            options={'verbose_name': 'Примененный промокод', 'verbose_name_plural': 'Примененные промокоды'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OP', 'Оплачен'), ('DL', 'Доставлен'), ('NP', 'Не оплачен'), ('DD', 'Выполняется доставка')], default='NP', max_length=2),
        ),
    ]
