# Generated by Django 4.2.5 on 2023-10-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_cart_promocode_alter_cart_items'),
        ('orders', '0003_alter_orderstatus_options_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='items.cartitem', verbose_name='Корзина'),
        ),
    ]
