# Generated by Django 4.2.5 on 2023-12-21 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='outer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
