# Generated by Django 4.2.5 on 2023-12-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_items_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='order_item_set', to='orders.orderitem', verbose_name='Предметы заказа'),
        ),
    ]
