# Generated by Django 4.2.5 on 2023-12-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('OP', 'Оплачен'), ('DL', 'Доставлен'), ('NP', 'Не оплачен'), ('DD', 'Выполняется доставка'), ('NA', 'Не активен')], default='NP', max_length=2, null=True, verbose_name='Статус заказа'),
        ),
    ]
