# Generated by Django 4.2.5 on 2023-12-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_transportcompany'),
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
    ]
