# Generated by Django 4.2.5 on 2023-12-24 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_transport_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='outer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='outer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='айди для банка'),
        ),
    ]
