# Generated by Django 5.0 on 2024-01-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_remove_promocode_sale_promocode_discount'),
        ('orders', '0013_order_payment_response_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='sale_price',
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='balance.promocode', verbose_name='Промокод'),
        ),
    ]
