# Generated by Django 5.0 on 2024-01-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_promocode_order_promocode_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='promocode_discount',
            new_name='promocode_discount_percentage',
        ),
    ]
