# Generated by Django 5.0 on 2024-01-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_rename_promocode_discount_order_promocode_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_discount',
            field=models.IntegerField(default=0, verbose_name='Скидка на товары'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='items_price_with_bonuses',
            field=models.IntegerField(default=0, verbose_name='Стоимость товаров с учетом бонусов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='items_price_with_promocode',
            field=models.IntegerField(default=0, verbose_name='Стоимость товаров с учетом промокода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='promocode_discount',
            field=models.IntegerField(default=0, verbose_name='Скидка по промокоду'),
            preserve_default=False,
        ),
    ]
